export const countries = {
  Germany: "DEU",
  Austria: "AUT",
  Belgium: "BEL",
  Bulgaria: "BGR",
  Cyprus: "CYP",
  Croatia: "HRV",
  Denmark: "DNK",
  Spain: "ESP",
  Estonia: "EST",
  Finland: "FIN",
  France: "FRA",
  Greece: "GRC",
  Hungary: "HUN",
  Ireland: "IRL",
  Italy: "ITA",
  Latvia: "LVA",
  Lithuania: "LTU",
  Luxembourg: "LUX",
  Malta: "MLT",
  Netherlands: "NLD",
  Poland: "POL",
  Portugal: "PRT",
  "Czech Republic": "CZE",
  Romania: "ROU",
  Slovakia: "SVK",
  Slovenia: "SVN",
  Sweden: "SWE",
  "United Kingdom": "GBR",
};

export type CountryCode = keyof typeof countries;